apiVersion: v1
kind: Service
metadata:
  name: genai-playground
  labels:
    app: genai-playground
spec:
  ports:
  - name: http
    port: 51001
    targetPort: 51001
  selector:
    app: genai-playground

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-playground
spec:
  selector:
    matchLabels:
      app: genai-playground
  replicas: 2
  template:
    metadata:
      labels:
        app: genai-playground
    spec:
      imagePullSecrets:
      - name: genai-playground-env-secret
      containers:
        - name: genai-playground
          image: woojinheo/genai-playground:latest
          ports:
          - containerPort: 51001
          env:
          - name: AICORE_BASE_URL
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: AICORE_BASE_URL
          - name: AICORE_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: AICORE_AUTH_URL
          - name: AICORE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: AICORE_CLIENT_ID
          - name: AICORE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: AICORE_CLIENT_SECRET
          - name: EMBEDDING_MODEL
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: EMBEDDING_MODEL
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: HOST
          - name: HANA_USERNAME
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: HANA_USERNAME
          - name: HANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: genai-playground-env-secret
                key: HANA_PASSWORD